export const services = [
  {
    id: "botox-treatment",
    title: "Botox Treatment",
    shortDescription: "Professional Botox injections for wrinkle reduction",
    description:
      "Botox is a non-invasive procedure that uses botulinum toxin to relax facial muscles and reduce the appearance of wrinkles and fine lines. Our expert doctors use FDA-approved products to provide natural-looking results.",
    benefits: [
      "Reduces fine lines and wrinkles",
      "Prevents new wrinkles from forming",
      "Non-invasive procedure",
      "Quick results in 3-7 days",
      "Results last 3-4 months",
    ],
    price: "Rs. 8,000 - Rs. 15,000",
    duration: "15-30 minutes",
    recovery: "No downtime",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Botox%20Treatment-EtqABygEqpN4cIRaAen5HDGvhvyf57.jpeg",
  },
  {
    id: "hydrafacial",
    title: "Hydrafacial Treatment",
    shortDescription: "Advanced hydradermabrasion for glowing skin",
    description:
      "Hydrafacial is a revolutionary treatment that uses patented vortex fusion technology to cleanse, extract, and hydrate your skin. It's suitable for all skin types and provides immediate results.",
    benefits: [
      "Deep skin cleansing",
      "Removes impurities and dead skin cells",
      "Hydrates and plumps skin",
      "Reduces fine lines",
      "Improves skin texture",
      "No downtime",
    ],
    price: "Rs. 5,000 - Rs. 12,000",
    duration: "30-45 minutes",
    recovery: "None",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Hydra%20facial-jQW1JWdqSWShEJyKZ1xOXrmVyf8qZM.jpeg",
  },
  {
    id: "laser-hair-removal",
    title: "Laser Hair Removal",
    shortDescription: "Permanent hair reduction with advanced laser technology",
    description:
      "Our laser hair removal treatment uses cutting-edge technology to permanently reduce unwanted hair. It's safe, effective, and suitable for all skin types.",
    benefits: [
      "Permanent hair reduction",
      "Fast treatment time",
      "Minimal discomfort",
      "Suitable for all skin types",
      "No ingrown hairs",
      "Long-lasting results",
    ],
    price: "Rs. 3,000 - Rs. 8,000 per session",
    duration: "15-45 minutes",
    recovery: "Minimal",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Laser%20Hair%20removal-yzwOJpnJxKLLJvtGUyMisF3FdIGOgt.png",
  },
  {
    id: "dermal-filler",
    title: "Dermal Filler Treatment",
    shortDescription: "Restore volume and enhance facial contours",
    description:
      "Dermal fillers add volume to areas of the face that have lost volume due to aging. They're perfect for enhancing lips, cheeks, and reducing nasolabial folds.",
    benefits: [
      "Restores facial volume",
      "Enhances lips and cheeks",
      "Reduces nasolabial folds",
      "Non-surgical",
      "Immediate results",
      "Lasts 6-12 months",
    ],
    price: "Rs. 10,000 - Rs. 25,000",
    duration: "30-45 minutes",
    recovery: "Minimal",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Dermal%20Filler-TuaYAM4WBs4nx3sKQo0nr8AOS1BT5S.jpeg",
  },
  {
    id: "microneedling",
    title: "Microneedling Treatment",
    shortDescription: "Collagen induction therapy for skin rejuvenation",
    description:
      "Microneedling uses fine needles to create controlled micro-injuries, stimulating natural collagen production. It's highly effective for acne scars, stretch marks, and skin texture.",
    benefits: [
      "Stimulates collagen production",
      "Reduces acne scars",
      "Improves skin texture",
      "Reduces stretch marks",
      "Tightens loose skin",
      "Minimal downtime",
    ],
    price: "Rs. 5,000 - Rs. 15,000",
    duration: "30-60 minutes",
    recovery: "3-5 days",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Micro%20needling-HDV96zSP20mZzH1R8ZmM7yaH2WBa7D.jpeg",
  },
  {
    id: "carbon-laser-peel",
    title: "Carbon Laser Peel",
    shortDescription: "Deep cleansing laser treatment for clear skin",
    description:
      "Carbon laser peel is a non-ablative laser treatment that deeply cleanses pores and stimulates collagen. It's ideal for acne-prone skin and provides immediate results.",
    benefits: [
      "Deep pore cleansing",
      "Kills acne bacteria",
      "Reduces acne and breakouts",
      "Improves skin tone",
      "Tightens pores",
      "No downtime",
    ],
    price: "Rs. 4,000 - Rs. 10,000",
    duration: "20-40 minutes",
    recovery: "None",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Carbon%20laser%20peel-UHa8TSM064khVb1mCszLkTHGsOPsAj.jpeg",
  },
  {
    id: "pigmentation-treatment",
    title: "Pigmentation Treatment",
    shortDescription: "Advanced treatment for dark spots and uneven tone",
    description:
      "Our pigmentation treatment targets melanin-producing cells to reduce dark spots, melasma, and uneven skin tone. We use advanced laser technology for safe and effective results.",
    benefits: [
      "Removes dark spots",
      "Treats melasma",
      "Evens skin tone",
      "Safe for all skin types",
      "Long-lasting results",
      "Non-invasive",
    ],
    price: "Rs. 6,000 - Rs. 15,000",
    duration: "20-45 minutes",
    recovery: "Minimal",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Pigmentation%20Treatment-SWgK4rNYySgRfxZNCFv1BGiBESVVvt.jpeg",
  },
  {
    id: "collagen-induction",
    title: "Collagen Induction Therapy",
    shortDescription: "Advanced microneedling for skin renewal",
    description:
      "Collagen Induction Therapy is an advanced form of microneedling that stimulates your skin's natural healing response. It's perfect for anti-aging and skin rejuvenation.",
    benefits: [
      "Stimulates collagen and elastin",
      "Reduces fine lines and wrinkles",
      "Improves skin elasticity",
      "Fills acne scars naturally",
      "Safe and effective",
      "Minimal side effects",
    ],
    price: "Rs. 8,000 - Rs. 18,000",
    duration: "45-60 minutes",
    recovery: "5-7 days",
    image:
      "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Collagen%20Induction-mH27Wtpna2E4MbrQ2NmcwDpiR4dBx6.jpeg",
  },
  {
    id: "acne-treatment",
    title: "Acne Treatment",
    shortDescription: "Professional acne clearing and prevention",
    description:
      "Our comprehensive acne treatment combines advanced technology with expert skincare. We address acne at its source while preventing future breakouts.",
    benefits: [
      "Clears existing acne",
      "Prevents future breakouts",
      "Reduces scars",
      "Kills acne bacteria",
      "Reduces inflammation",
      "Fast results",
    ],
    price: "Rs. 3,000 - Rs. 10,000",
    duration: "30-45 minutes",
    recovery: "Minimal",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/doctor-b8l03qVHvPTzSlhaHCQtafOJEcNQkv.png",
  },
  {
    id: "pigmentation",
    title: "Treatment For Pigmentation",
    shortDescription: "Specialized pigmentation management",
    description:
      "Expert treatment for hyperpigmentation, melasma, and post-inflammatory hyperpigmentation using advanced laser and light therapies.",
    benefits: [
      "Targets pigmented lesions",
      "Even skin tone",
      "Safe for darker skin types",
      "Customized treatment plans",
      "Visible results quickly",
      "Professional supervision",
    ],
    price: "Rs. 6,000 - Rs. 12,000",
    duration: "30-45 minutes",
    recovery: "Minimal",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Pigmentation%20Treatment-or33JgiPsTosGbf0hdc6k3T7iDy7Sh.jpeg",
  },
  {
    id: "hair-growth",
    title: "Treatment For Hair Growth",
    shortDescription: "Advanced hair restoration therapy",
    description:
      "Our hair growth treatments use advanced technology and scientifically-proven methods to stimulate hair growth and prevent hair loss.",
    benefits: [
      "Stimulates new hair growth",
      "Strengthens existing hair",
      "Prevents further hair loss",
      "Improves hair thickness",
      "Natural-looking results",
      "No side effects",
    ],
    price: "Rs. 5,000 - Rs. 15,000",
    duration: "45-60 minutes",
    recovery: "None",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Treatment%20for%20hair%20growth-Pb0qcoCJNVJnwn5DR2KEeLmTaEX1OV.jpeg",
  },
  {
    id: "prp-therapy",
    title: "PRP Therapy",
    shortDescription: "Platelet-rich plasma for natural rejuvenation",
    description:
      "PRP uses your own blood's growth factors to rejuvenate skin and stimulate collagen production. It's a natural and effective anti-aging treatment.",
    benefits: [
      "Uses your own blood",
      "Stimulates collagen",
      "Improves skin texture",
      "Reduces fine lines",
      "Natural results",
      "Long-lasting effects",
    ],
    price: "Rs. 10,000 - Rs. 20,000",
    duration: "60 minutes",
    recovery: "1-2 days",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/doctor-b8l03qVHvPTzSlhaHCQtafOJEcNQkv.png",
  },
  {
    id: "chemical-peeling",
    title: "Chemical Peeling",
    shortDescription: "Advanced chemical exfoliation for clear skin",
    description:
      "Chemical peels use acids to remove damaged outer skin layers, revealing fresh, glowing skin underneath. Available in various strengths for different skin concerns.",
    benefits: [
      "Removes dead skin cells",
      "Improves skin texture",
      "Reduces age spots",
      "Treats acne scars",
      "Brightens complexion",
      "Visible results",
    ],
    price: "Rs. 3,000 - Rs. 8,000",
    duration: "20-30 minutes",
    recovery: "3-7 days",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/doctor-b8l03qVHvPTzSlhaHCQtafOJEcNQkv.png",
  },
  {
    id: "wart-removal",
    title: "Wart Removal",
    shortDescription: "Safe and effective wart removal",
    description:
      "Our advanced wart removal techniques safely eliminate warts without scarring. We use multiple treatment options for best results.",
    benefits: [
      "Safe removal",
      "Minimal scarring",
      "Quick procedure",
      "High success rate",
      "Prevents recurrence",
      "Professional expertise",
    ],
    price: "Rs. 2,000 - Rs. 5,000",
    duration: "15-30 minutes",
    recovery: "1-2 weeks",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/doctor-b8l03qVHvPTzSlhaHCQtafOJEcNQkv.png",
  },
  {
    id: "fat-burning",
    title: "Fat Burning Treatment",
    shortDescription: "Non-invasive fat reduction technology",
    description:
      "Our advanced fat burning treatments use non-invasive technology to reduce localized fat deposits. Perfect for body contouring without surgery.",
    benefits: [
      "Non-invasive",
      "Targets stubborn fat",
      "No downtime",
      "Boosts metabolism",
      "Visible results in weeks",
      "Safe procedure",
    ],
    price: "Rs. 5,000 - Rs. 12,000",
    duration: "45-60 minutes",
    recovery: "None",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/doctor-b8l03qVHvPTzSlhaHCQtafOJEcNQkv.png",
  },
];

export type Service = (typeof services)[0];
